config/routes.rb
Rails.application.routes.draw do
  resources :kittens

  root 'kittens#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    respond_to do |format|
      if @kitten.save
        format.html { redirect_to @kitten, notice: "Look a brand new kitten!"}

      else
        format.html { render :new }

      end
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def edit
  end

  def update
    
    respond_to do |format|
      if @kitten.update_attributes(kitten_params)
        format.html { redirect_to @kitten, notice: "#{@kitten.name} has been updated" }

      else
        format.html { render :edit }
      end
    end
  end

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def destroy
    
    @kitten.destroy
    respond_to do |format|
      format.html { redirect_to kittens_url, notice: "A kitten has been destroyed... NOOOOO!" }

    end
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for(@kitten) do |f| %>
    
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %><br>

    <%= f.label :age %>
    <%= f.number_field :age, class: 'form-control' %><br>

    <%= f.label :cuteness %>
    <%= f.text_field :cuteness, class: 'form-control' %><br>

    <%= f.label :softness %>
    <%= f.text_field :softness, class: 'form-control' %><br>

    <%= f.submit 'Save', class: "btn btn-primary" %>
  <% end %>

app/views/kittens/_kitten.html.erb
<p class='kitten'><%= kitten.name %> is <%= "#{pluralize(kitten.age, 'year')}" %> old and is <%= kitten.cuteness %> and soft as <%= kitten.softness %></p>
<%= link_to 'edit', edit_kitten_path(kitten) %> <%= link_to 'delete', kitten, method: :delete, data: { confirm: 'Really?' } %>

app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

app/views/kittens/destroy.html.erb
<h1>Kittens#destroy</h1>
<p>Find me in app/views/kittens/destroy.html.erb</p>

app/views/kittens/edit.html.erb
<h1>Edit <%= @kitten.name %></h1>
<%= render 'form' %>
<%= link_to 'delete', @kitten, method: :delete, data: { confirm: 'Really?' } %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>

<ul class='kittens'>
	<% @kittens.each do |kitten| %>
	<li><%= link_to kitten.name, kitten %>
		<%= link_to 'delete', kitten, method: :delete, data: { confirm: 'Really?' } %>
	</li>
	<% end %>
</ul>
<%= link_to 'New Kitten', new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>
<%= render 'form' %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<%= render @kitten %>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
  	</div>
    <%= yield %>
  </body>
</html>